// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIJ3oxO_EjuSB-0r1CqNmk7e1oBVCiJsE',
    appId: '1:1032252473086:web:ad72f83108a0ae47a52faf',
    messagingSenderId: '1032252473086',
    projectId: 'mp-amc',
    authDomain: 'mp-amc.firebaseapp.com',
    databaseURL: 'https://mp-amc-default-rtdb.firebaseio.com',
    storageBucket: 'mp-amc.firebasestorage.app',
    measurementId: 'G-NLSVNTS9YZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBmeinH_x3ka209an6TkOGx8A-L9yf7qiE',
    appId: '1:1032252473086:android:55eccc81322b432da52faf',
    messagingSenderId: '1032252473086',
    projectId: 'mp-amc',
    databaseURL: 'https://mp-amc-default-rtdb.firebaseio.com',
    storageBucket: 'mp-amc.firebasestorage.app',
  );

}